name: shell commands
'on':
  - push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello World"
      - name: echo string
        run: echo "DevOps!"
      - name: Multi line string
        run: |
          pwd
          node -v
          ls -a
